# Generated by Django 4.1.2 on 2022-10-08 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construcJob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('certificado', 'Si Certificado'), ('libre', 'Independiente')], default='libre', max_length=20)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_de_Empleador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.CharField(choices=[('Hr', 'Horas'), ('Di', 'Dias')], default='Hr', max_length=2)),
                ('disponible', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcJob.categoriajobs')),
            ],
        ),
        migrations.CreateModel(
            name='ListaTrabajosDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('Remuneracion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcJob.contratista')),
                ('Trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcJob.trabajo')),
            ],
        ),
    ]
