# Generated by Django 4.1.2 on 2022-10-08 02:15

import construcJob.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construcJob', '0003_alter_trabajo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listatrabajosdisponibles',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[construcJob.validators.validarInter]),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[construcJob.validators.validarInter, construcJob.validators.validarJornal]),
        ),
    ]
